### ISSUE TITLE
Multiplication & division algorithm

### ISSUE THREAD

**Issue by TeoTN** [robin92/jftt2014-compiler#14]
Hi! Could you explain multiplication and division algorithms you use?

**Comment by robin92** [comment]
As far as I can remember this is a standard multiplication algorithm (in columns) as taught in primary schools. The only difference is number base - it's base 2 (binary numbers). This allows for adding only when multiplicand *n*th bit equals 1.

The same goes for division algorithm. What's funny tough, is the fact that our Professor made a VM with only 3 fast registers whereas in division you need at least 4 such registers to store some values.

Also please note that assembly language is nothing commonly known. It's a special language made up only for our classes purposes.
